package tn.amin.mpro2.features;

public enum FeatureId {
    INTERNAL_THREADKEY_DETECTOR,
    INTERNAL_HISTORY_MEDIA_CAPTURE,

    SETTINGS_LAUNCH,
    UNSEEN,
    UNTYPING,
    PRESENCE_STEALTH,
    TYPING,
    FORMATTING,
    FILE_ATTACH,
    CONV_LOCK,
    THREADKEY_COPY,
    DEFAULT_CAMERA,
    TASKER_TYPING_INDICATOR_RECEIVED,
    TASKER_MESSAGE_RECEIVED,
    MEDIA_TRANSCODER,
    VIDEO_DOWNLOAD
}
