package tn.amin.mpro2.hook;

public enum HookId {
    SEEN_INDICATOR_SEND,
    MESSAGE_SEND,
    MESSAGE_RECEIVE,
    TYPING_INDICATOR_SEND,
    TYPING_INDICATOR_RECEIVE,
    PRESENCE_STATUS_SEND,
    CONVERSATION_ENTER,
    CONVERSATION_LEAVE,
    CAMERA_LAUNCH,
    MESSAGES_DISPLAY,
    MEDIA_TRANSCODER,
    ALLOW_SCREEN_CAPTURE,
    BLOCK_SCREENSHOT_DETECTION,
    OPEN_LINKS_EXTERNALLY
}
